name: deploy-action
description: 'docker deploy action'
inputs:
  stack-prefix:
    description: 'Prefix for the stack name'
    required: true
  stack-name:
    description: 'Name of the stack to deploy'
    required: true
  docker-stack-file:
    description: 'Path to the Docker stack file'
    required: true
  app-image:
    description: 'Docker image to deploy'
    required: true
  host:
    description: 'SSH host for deployment'
    required: true
  user:
    description: 'SSH user for deployment'
    required: true
  ssh-key:
    description: 'SSH private key for deployment'
    required: true
  docker-registry:
    description: 'Docker registry'
    required: true
    default: "ghcr.io"
  docker-username:
    description: 'Docker registry username'
    required: true
  docker-password:
    description: 'Docker registry password'
    required: true  
  detach:
    description: 'Detach mode for stack deploy'
    required: false
    default: "false"
  

     
runs:
  using: "composite"
  steps:
    - name: setup deploy stack vars
      shell: bash
      run: |
        mkdir -p "$HOME/.ssh"
        KEY_FILE="$HOME/.ssh/id_ed25519"

        echo "${{ inputs.ssh-key }}" > "$KEY_FILE"

        echo "SSH_KEY_FILE=$KEY_FILE" >> "$GITHUB_ENV"

        chmod 400 "$KEY_FILE"
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    - name: deploy stack
      shell: bash
      run: |
        export STACK="${{ inputs.stack-prefix }}-${{ inputs.stack-name }}"

        docker stack config -c "${{ inputs.docker-stack-file }}"

        ssh-keyscan "${{ inputs.host }}" >> "$HOME/.ssh/known_hosts"
        
        docker context create deploy --docker \
        "host=ssh://${{ inputs.user }}@${{ inputs.host }},key=${KEY_FILE}"           

        docker context use deploy
        docker network inspect ${STACK}_infra-net >/dev/null 2>&1 || \
        docker network create \
        --driver overlay \
        --scope swarm \
        --attachable \
        --opt encrypted \
        ${STACK}_infra-net
        docker network ls
        docker stack deploy --detach="${{ inputs.detach }}" --with-registry-auth -c "${{ inputs.docker-stack-file }}" "${STACK}"
        docker stack ls
        docker stack ps "${STACK}" --no-trunc